-- GENERATED by The Warehouse (warehouse roblox build). Do not edit by hand; edit scenes/ and rebuild.
local Sprites = {}

Sprites.Sheets = {
	[1] = { Id = "rbxassetid://125789431816942", Width = 128, Height = 128 },
}

Sprites.Sprites = {
	["bed"] = { Sheet = 1, X = 1, Y = 1, W = 16, H = 16 },
	["cave"] = { Sheet = 1, X = 18, Y = 1, W = 16, H = 16 },
	["farm"] = { Sheet = 1, X = 35, Y = 1, W = 16, H = 16 },
	["ford"] = { Sheet = 1, X = 52, Y = 1, W = 16, H = 16 },
	["gate"] = { Sheet = 1, X = 69, Y = 1, W = 16, H = 16 },
	["grass"] = { Sheet = 1, X = 86, Y = 1, W = 16, H = 16 },
	["grass_2"] = { Sheet = 1, X = 103, Y = 1, W = 16, H = 16 },
	["hut"] = { Sheet = 1, X = 1, Y = 18, W = 16, H = 16 },
	["hut_burnt"] = { Sheet = 1, X = 18, Y = 18, W = 16, H = 16 },
	["path"] = { Sheet = 1, X = 35, Y = 18, W = 16, H = 16 },
	["player_down_0"] = { Sheet = 1, X = 52, Y = 18, W = 16, H = 16 },
	["player_down_1"] = { Sheet = 1, X = 69, Y = 18, W = 16, H = 16 },
	["player_left_0"] = { Sheet = 1, X = 86, Y = 18, W = 16, H = 16 },
	["player_left_1"] = { Sheet = 1, X = 103, Y = 18, W = 16, H = 16 },
	["player_right_0"] = { Sheet = 1, X = 1, Y = 35, W = 16, H = 16 },
	["player_right_1"] = { Sheet = 1, X = 18, Y = 35, W = 16, H = 16 },
	["player_up_0"] = { Sheet = 1, X = 35, Y = 35, W = 16, H = 16 },
	["player_up_1"] = { Sheet = 1, X = 52, Y = 35, W = 16, H = 16 },
	["rock"] = { Sheet = 1, X = 69, Y = 35, W = 16, H = 16 },
	["stall"] = { Sheet = 1, X = 86, Y = 35, W = 16, H = 16 },
	["tall_grass"] = { Sheet = 1, X = 103, Y = 35, W = 16, H = 16 },
	["tree"] = { Sheet = 1, X = 1, Y = 52, W = 16, H = 16 },
	["wall"] = { Sheet = 1, X = 18, Y = 52, W = 16, H = 16 },
	["water"] = { Sheet = 1, X = 35, Y = 52, W = 16, H = 16 },
}

--- Point an ImageLabel/ImageButton at a named sprite. Keeps pixels crisp.
function Sprites.Apply(image: ImageLabel | ImageButton, spriteName: string)
	local s = Sprites.Sprites[spriteName]
	if not s then warn("[Sprites] unknown sprite " .. tostring(spriteName)) return end
	local sheet = Sprites.Sheets[s.Sheet]
	image.Image = sheet.Id
	image.ImageRectOffset = Vector2.new(s.X, s.Y)
	image.ImageRectSize = Vector2.new(s.W, s.H)
	image.ResampleMode = Enum.ResamplerMode.Pixelated
	image.ScaleType = Enum.ScaleType.Stretch
end

--- Create a new ImageLabel showing a sprite.
function Sprites.New(spriteName: string, parent: Instance?): ImageLabel
	local img = Instance.new("ImageLabel")
	img.BackgroundTransparency = 1
	img.BorderSizePixel = 0
	img.Name = spriteName
	Sprites.Apply(img, spriteName)
	if parent then img.Parent = parent end
	return img
end

function Sprites.Has(spriteName: string): boolean return Sprites.Sprites[spriteName] ~= nil end

--- SERVER ONLY. Open Cloud uploads give a Decal id; ImageLabels need the Image id inside it, and Roblox
--- will not tell outsiders which is which. The server can load its own decal and read the texture off it.
--- Call once at startup, then send Sheets ids to clients (see WorldInit) so everyone uses the resolved ids.
function Sprites.ResolveOnServer(): { [number]: string }
	local InsertService = game:GetService("InsertService")
	local out = {}
	for i, sheet in ipairs(Sprites.Sheets) do
		local id = tonumber(string.match(sheet.Id, "%d+"))
		if id and id > 0 and not sheet.Resolved then
			local ok, model = pcall(function() return InsertService:LoadAsset(id) end)
			if ok and model then
				local decal = model:FindFirstChildWhichIsA("Decal", true)
				local texture = if decal then decal.Texture else ""
				local imageId = string.match(texture, "[?&]id=(%d+)") or string.match(texture, "rbxassetid://(%d+)")
				if imageId then
					sheet.Id = "rbxassetid://" .. imageId
					sheet.Resolved = true
					print(("[Sprites] sheet %d: decal %d -> image %s"):format(i, id, imageId))
				else
					-- No decal inside: the id is already an image id (setid was used). Keep it.
					sheet.Resolved = true
				end
				model:Destroy()
			else
				warn(("[Sprites] could not load asset %d to resolve it (%s); using it as is"):format(id, tostring(model)))
			end
		end
		out[i] = sheet.Id
	end
	return out
end

--- CLIENT: apply the ids the server resolved before building any UI.
function Sprites.ApplySheetIds(ids: { [number]: string }?)
	if not ids then return end
	for i, id in pairs(ids) do
		if Sprites.Sheets[i] and type(id) == "string" then Sprites.Sheets[i].Id = id end
	end
end

return Sprites
