-- GENERATED by The Warehouse (warehouse roblox build). Do not edit by hand; edit scenes/ and rebuild.
local Sprites = {}

Sprites.Sheets = {
	[1] = { Id = "rbxassetid://82793847565859", Width = 256, Height = 512, Resolved = true },
}

Sprites.Sprites = {
	["abandoned_tent"] = { Sheet = 1, X = 50, Y = 66, W = 32, H = 32 },
	["arrows_in_ground"] = { Sheet = 1, X = 34, Y = 132, W = 16, H = 16 },
	["ash_pile"] = { Sheet = 1, X = 51, Y = 132, W = 16, H = 16 },
	["baby_down_0"] = { Sheet = 1, X = 68, Y = 132, W = 16, H = 16 },
	["baby_down_1"] = { Sheet = 1, X = 85, Y = 132, W = 16, H = 16 },
	["bag"] = { Sheet = 1, X = 102, Y = 132, W = 16, H = 16 },
	["bandit_down_0"] = { Sheet = 1, X = 119, Y = 132, W = 16, H = 16 },
	["bandit_down_1"] = { Sheet = 1, X = 136, Y = 132, W = 16, H = 16 },
	["bandit_left_0"] = { Sheet = 1, X = 153, Y = 132, W = 16, H = 16 },
	["bandit_left_1"] = { Sheet = 1, X = 170, Y = 132, W = 16, H = 16 },
	["bandit_right_0"] = { Sheet = 1, X = 187, Y = 132, W = 16, H = 16 },
	["bandit_right_1"] = { Sheet = 1, X = 204, Y = 132, W = 16, H = 16 },
	["bandit_up_0"] = { Sheet = 1, X = 221, Y = 132, W = 16, H = 16 },
	["bandit_up_1"] = { Sheet = 1, X = 238, Y = 132, W = 16, H = 16 },
	["barn"] = { Sheet = 1, X = 1, Y = 1, W = 48, H = 64 },
	["battle_debris"] = { Sheet = 1, X = 1, Y = 149, W = 16, H = 16 },
	["bed"] = { Sheet = 1, X = 18, Y = 149, W = 16, H = 16 },
	["beehive"] = { Sheet = 1, X = 35, Y = 149, W = 16, H = 16 },
	["berry_bush"] = { Sheet = 1, X = 52, Y = 149, W = 16, H = 16 },
	["boar_left_0"] = { Sheet = 1, X = 69, Y = 149, W = 16, H = 16 },
	["boar_left_1"] = { Sheet = 1, X = 86, Y = 149, W = 16, H = 16 },
	["boar_right_0"] = { Sheet = 1, X = 103, Y = 149, W = 16, H = 16 },
	["boar_right_1"] = { Sheet = 1, X = 120, Y = 149, W = 16, H = 16 },
	["bones"] = { Sheet = 1, X = 137, Y = 149, W = 16, H = 16 },
	["boulder"] = { Sheet = 1, X = 154, Y = 149, W = 16, H = 16 },
	["boulder_mossy"] = { Sheet = 1, X = 171, Y = 149, W = 16, H = 16 },
	["broken_cart"] = { Sheet = 1, X = 170, Y = 99, W = 32, H = 16 },
	["broken_fence"] = { Sheet = 1, X = 188, Y = 149, W = 16, H = 16 },
	["broken_wall"] = { Sheet = 1, X = 205, Y = 149, W = 16, H = 16 },
	["bush"] = { Sheet = 1, X = 222, Y = 149, W = 16, H = 16 },
	["cage"] = { Sheet = 1, X = 239, Y = 149, W = 16, H = 16 },
	["camp_lit_0"] = { Sheet = 1, X = 1, Y = 166, W = 16, H = 16 },
	["camp_lit_1"] = { Sheet = 1, X = 18, Y = 166, W = 16, H = 16 },
	["camp_out"] = { Sheet = 1, X = 35, Y = 166, W = 16, H = 16 },
	["cart"] = { Sheet = 1, X = 203, Y = 99, W = 32, H = 16 },
	["cave"] = { Sheet = 1, X = 52, Y = 166, W = 16, H = 16 },
	["dead_tree"] = { Sheet = 1, X = 69, Y = 166, W = 16, H = 16 },
	["dead_tree_tall"] = { Sheet = 1, X = 165, Y = 1, W = 16, H = 48 },
	["deer_left_0"] = { Sheet = 1, X = 86, Y = 166, W = 16, H = 16 },
	["deer_left_1"] = { Sheet = 1, X = 103, Y = 166, W = 16, H = 16 },
	["deer_right_0"] = { Sheet = 1, X = 120, Y = 166, W = 16, H = 16 },
	["deer_right_1"] = { Sheet = 1, X = 137, Y = 166, W = 16, H = 16 },
	["drying_rack"] = { Sheet = 1, X = 154, Y = 166, W = 16, H = 16 },
	["fallen_log"] = { Sheet = 1, X = 171, Y = 166, W = 16, H = 16 },
	["farm"] = { Sheet = 1, X = 188, Y = 166, W = 16, H = 16 },
	["flood"] = { Sheet = 1, X = 205, Y = 166, W = 16, H = 16 },
	["flower_purple"] = { Sheet = 1, X = 222, Y = 166, W = 16, H = 16 },
	["flower_red"] = { Sheet = 1, X = 239, Y = 166, W = 16, H = 16 },
	["flower_white"] = { Sheet = 1, X = 1, Y = 183, W = 16, H = 16 },
	["ford"] = { Sheet = 1, X = 18, Y = 183, W = 16, H = 16 },
	["gate"] = { Sheet = 1, X = 35, Y = 183, W = 16, H = 16 },
	["granary"] = { Sheet = 1, X = 83, Y = 66, W = 32, H = 32 },
	["grass"] = { Sheet = 1, X = 52, Y = 183, W = 16, H = 16 },
	["grass_2"] = { Sheet = 1, X = 69, Y = 183, W = 16, H = 16 },
	["grave_cross"] = { Sheet = 1, X = 86, Y = 183, W = 16, H = 16 },
	["guard_down_0"] = { Sheet = 1, X = 103, Y = 183, W = 16, H = 16 },
	["guard_down_1"] = { Sheet = 1, X = 120, Y = 183, W = 16, H = 16 },
	["guard_left_0"] = { Sheet = 1, X = 137, Y = 183, W = 16, H = 16 },
	["guard_left_1"] = { Sheet = 1, X = 154, Y = 183, W = 16, H = 16 },
	["guard_right_0"] = { Sheet = 1, X = 171, Y = 183, W = 16, H = 16 },
	["guard_right_1"] = { Sheet = 1, X = 188, Y = 183, W = 16, H = 16 },
	["guard_up_0"] = { Sheet = 1, X = 205, Y = 183, W = 16, H = 16 },
	["guard_up_1"] = { Sheet = 1, X = 222, Y = 183, W = 16, H = 16 },
	["hay_bale"] = { Sheet = 1, X = 239, Y = 183, W = 16, H = 16 },
	["heart"] = { Sheet = 1, X = 1, Y = 200, W = 16, H = 16 },
	["heart_empty"] = { Sheet = 1, X = 18, Y = 200, W = 16, H = 16 },
	["heart_half"] = { Sheet = 1, X = 35, Y = 200, W = 16, H = 16 },
	["hiring_board"] = { Sheet = 1, X = 52, Y = 200, W = 16, H = 16 },
	["hunter_down_0"] = { Sheet = 1, X = 69, Y = 200, W = 16, H = 16 },
	["hunter_down_1"] = { Sheet = 1, X = 86, Y = 200, W = 16, H = 16 },
	["hunter_left_0"] = { Sheet = 1, X = 103, Y = 200, W = 16, H = 16 },
	["hunter_left_1"] = { Sheet = 1, X = 120, Y = 200, W = 16, H = 16 },
	["hunter_right_0"] = { Sheet = 1, X = 137, Y = 200, W = 16, H = 16 },
	["hunter_right_1"] = { Sheet = 1, X = 154, Y = 200, W = 16, H = 16 },
	["hunter_up_0"] = { Sheet = 1, X = 171, Y = 200, W = 16, H = 16 },
	["hunter_up_1"] = { Sheet = 1, X = 188, Y = 200, W = 16, H = 16 },
	["hut"] = { Sheet = 1, X = 205, Y = 200, W = 16, H = 16 },
	["hut_burnt"] = { Sheet = 1, X = 222, Y = 200, W = 16, H = 16 },
	["hut_hunter"] = { Sheet = 1, X = 239, Y = 200, W = 16, H = 16 },
	["hut_plunderer"] = { Sheet = 1, X = 1, Y = 217, W = 16, H = 16 },
	["item_camper"] = { Sheet = 1, X = 18, Y = 217, W = 16, H = 16 },
	["item_coin"] = { Sheet = 1, X = 35, Y = 217, W = 16, H = 16 },
	["item_food"] = { Sheet = 1, X = 52, Y = 217, W = 16, H = 16 },
	["item_hide"] = { Sheet = 1, X = 69, Y = 217, W = 16, H = 16 },
	["item_knife"] = { Sheet = 1, X = 86, Y = 217, W = 16, H = 16 },
	["item_ore"] = { Sheet = 1, X = 103, Y = 217, W = 16, H = 16 },
	["item_tool"] = { Sheet = 1, X = 120, Y = 217, W = 16, H = 16 },
	["item_waterskin"] = { Sheet = 1, X = 137, Y = 217, W = 16, H = 16 },
	["knights_post"] = { Sheet = 1, X = 34, Y = 99, W = 16, H = 32 },
	["lantern_post"] = { Sheet = 1, X = 154, Y = 217, W = 16, H = 16 },
	["longhouse"] = { Sheet = 1, X = 182, Y = 1, W = 48, H = 32 },
	["lookout_tree"] = { Sheet = 1, X = 99, Y = 1, W = 32, H = 48 },
	["loot_heap"] = { Sheet = 1, X = 171, Y = 217, W = 16, H = 16 },
	["marker"] = { Sheet = 1, X = 188, Y = 217, W = 16, H = 16 },
	["marker_arrow"] = { Sheet = 1, X = 205, Y = 217, W = 16, H = 16 },
	["market_awning"] = { Sheet = 1, X = 222, Y = 217, W = 16, H = 16 },
	["merchant_down_0"] = { Sheet = 1, X = 239, Y = 217, W = 16, H = 16 },
	["merchant_down_1"] = { Sheet = 1, X = 1, Y = 234, W = 16, H = 16 },
	["merchant_left_0"] = { Sheet = 1, X = 18, Y = 234, W = 16, H = 16 },
	["merchant_left_1"] = { Sheet = 1, X = 35, Y = 234, W = 16, H = 16 },
	["merchant_right_0"] = { Sheet = 1, X = 52, Y = 234, W = 16, H = 16 },
	["merchant_right_1"] = { Sheet = 1, X = 69, Y = 234, W = 16, H = 16 },
	["merchant_up_0"] = { Sheet = 1, X = 86, Y = 234, W = 16, H = 16 },
	["merchant_up_1"] = { Sheet = 1, X = 103, Y = 234, W = 16, H = 16 },
	["mushrooms"] = { Sheet = 1, X = 120, Y = 234, W = 16, H = 16 },
	["muster_ring"] = { Sheet = 1, X = 116, Y = 66, W = 32, H = 32 },
	["palisade"] = { Sheet = 1, X = 137, Y = 234, W = 16, H = 16 },
	["palisade_gate"] = { Sheet = 1, X = 154, Y = 234, W = 16, H = 16 },
	["path"] = { Sheet = 1, X = 171, Y = 234, W = 16, H = 16 },
	["pine"] = { Sheet = 1, X = 51, Y = 99, W = 16, H = 32 },
	["pine_tall"] = { Sheet = 1, X = 68, Y = 99, W = 16, H = 32 },
	["player_down_0"] = { Sheet = 1, X = 188, Y = 234, W = 16, H = 16 },
	["player_down_1"] = { Sheet = 1, X = 205, Y = 234, W = 16, H = 16 },
	["player_left_0"] = { Sheet = 1, X = 222, Y = 234, W = 16, H = 16 },
	["player_left_1"] = { Sheet = 1, X = 239, Y = 234, W = 16, H = 16 },
	["player_right_0"] = { Sheet = 1, X = 1, Y = 251, W = 16, H = 16 },
	["player_right_1"] = { Sheet = 1, X = 18, Y = 251, W = 16, H = 16 },
	["player_up_0"] = { Sheet = 1, X = 35, Y = 251, W = 16, H = 16 },
	["player_up_1"] = { Sheet = 1, X = 52, Y = 251, W = 16, H = 16 },
	["reeds"] = { Sheet = 1, X = 69, Y = 251, W = 16, H = 16 },
	["river_0"] = { Sheet = 1, X = 86, Y = 251, W = 16, H = 16 },
	["river_1"] = { Sheet = 1, X = 103, Y = 251, W = 16, H = 16 },
	["roadside_shrine"] = { Sheet = 1, X = 85, Y = 99, W = 16, H = 32 },
	["rock"] = { Sheet = 1, X = 120, Y = 251, W = 16, H = 16 },
	["rocks_brown"] = { Sheet = 1, X = 137, Y = 251, W = 16, H = 16 },
	["rocks_grey"] = { Sheet = 1, X = 154, Y = 251, W = 16, H = 16 },
	["rubble"] = { Sheet = 1, X = 171, Y = 251, W = 16, H = 16 },
	["ruined_watchtower"] = { Sheet = 1, X = 102, Y = 99, W = 16, H = 32 },
	["scarecrow"] = { Sheet = 1, X = 188, Y = 251, W = 16, H = 16 },
	["scorched_ground"] = { Sheet = 1, X = 205, Y = 251, W = 16, H = 16 },
	["sign"] = { Sheet = 1, X = 222, Y = 251, W = 16, H = 16 },
	["skull"] = { Sheet = 1, X = 239, Y = 251, W = 16, H = 16 },
	["skull_post"] = { Sheet = 1, X = 1, Y = 268, W = 16, H = 16 },
	["smokehouse"] = { Sheet = 1, X = 119, Y = 99, W = 16, H = 32 },
	["stall"] = { Sheet = 1, X = 18, Y = 268, W = 16, H = 16 },
	["stockade"] = { Sheet = 1, X = 1, Y = 132, W = 32, H = 16 },
	["stockade_gate"] = { Sheet = 1, X = 35, Y = 268, W = 16, H = 16 },
	["storehouse"] = { Sheet = 1, X = 149, Y = 66, W = 32, H = 32 },
	["stump"] = { Sheet = 1, X = 52, Y = 268, W = 16, H = 16 },
	["tall_grass"] = { Sheet = 1, X = 69, Y = 268, W = 16, H = 16 },
	["tannery"] = { Sheet = 1, X = 182, Y = 66, W = 32, H = 32 },
	["tent"] = { Sheet = 1, X = 215, Y = 66, W = 32, H = 32 },
	["tombstone"] = { Sheet = 1, X = 86, Y = 268, W = 16, H = 16 },
	["totem"] = { Sheet = 1, X = 103, Y = 268, W = 16, H = 16 },
	["town_hall"] = { Sheet = 1, X = 50, Y = 1, W = 48, H = 48 },
	["tree"] = { Sheet = 1, X = 120, Y = 268, W = 16, H = 16 },
	["tree_autumn"] = { Sheet = 1, X = 136, Y = 99, W = 16, H = 32 },
	["trophy_hall"] = { Sheet = 1, X = 1, Y = 99, W = 32, H = 32 },
	["ui_arrow"] = { Sheet = 1, X = 137, Y = 268, W = 16, H = 16 },
	["villager_down_0"] = { Sheet = 1, X = 154, Y = 268, W = 16, H = 16 },
	["villager_down_1"] = { Sheet = 1, X = 171, Y = 268, W = 16, H = 16 },
	["villager_left_0"] = { Sheet = 1, X = 188, Y = 268, W = 16, H = 16 },
	["villager_left_1"] = { Sheet = 1, X = 205, Y = 268, W = 16, H = 16 },
	["villager_preg_down_0"] = { Sheet = 1, X = 222, Y = 268, W = 16, H = 16 },
	["villager_preg_down_1"] = { Sheet = 1, X = 239, Y = 268, W = 16, H = 16 },
	["villager_preg_left_0"] = { Sheet = 1, X = 1, Y = 285, W = 16, H = 16 },
	["villager_preg_left_1"] = { Sheet = 1, X = 18, Y = 285, W = 16, H = 16 },
	["villager_preg_right_0"] = { Sheet = 1, X = 35, Y = 285, W = 16, H = 16 },
	["villager_preg_right_1"] = { Sheet = 1, X = 52, Y = 285, W = 16, H = 16 },
	["villager_preg_up_0"] = { Sheet = 1, X = 69, Y = 285, W = 16, H = 16 },
	["villager_preg_up_1"] = { Sheet = 1, X = 86, Y = 285, W = 16, H = 16 },
	["villager_right_0"] = { Sheet = 1, X = 103, Y = 285, W = 16, H = 16 },
	["villager_right_1"] = { Sheet = 1, X = 120, Y = 285, W = 16, H = 16 },
	["villager_up_0"] = { Sheet = 1, X = 137, Y = 285, W = 16, H = 16 },
	["villager_up_1"] = { Sheet = 1, X = 154, Y = 285, W = 16, H = 16 },
	["wall"] = { Sheet = 1, X = 171, Y = 285, W = 16, H = 16 },
	["war_hall"] = { Sheet = 1, X = 1, Y = 66, W = 48, H = 32 },
	["watchtower"] = { Sheet = 1, X = 153, Y = 99, W = 16, H = 32 },
	["water_0"] = { Sheet = 1, X = 188, Y = 285, W = 16, H = 16 },
	["water_1"] = { Sheet = 1, X = 205, Y = 285, W = 16, H = 16 },
	["well"] = { Sheet = 1, X = 222, Y = 285, W = 16, H = 16 },
	["windmill"] = { Sheet = 1, X = 132, Y = 1, W = 32, H = 48 },
	["wolf_left_0"] = { Sheet = 1, X = 239, Y = 285, W = 16, H = 16 },
	["wolf_left_1"] = { Sheet = 1, X = 1, Y = 302, W = 16, H = 16 },
	["wolf_right_0"] = { Sheet = 1, X = 18, Y = 302, W = 16, H = 16 },
	["wolf_right_1"] = { Sheet = 1, X = 35, Y = 302, W = 16, H = 16 },
	["woodpile"] = { Sheet = 1, X = 52, Y = 302, W = 16, H = 16 },
}

--- Point an ImageLabel/ImageButton at a named sprite. Keeps pixels crisp.
function Sprites.Apply(image: ImageLabel | ImageButton, spriteName: string)
	local s = Sprites.Sprites[spriteName]
	if not s then warn("[Sprites] unknown sprite " .. tostring(spriteName)) return end
	local sheet = Sprites.Sheets[s.Sheet]
	image.Image = sheet.Id
	image.ImageRectOffset = Vector2.new(s.X, s.Y)
	image.ImageRectSize = Vector2.new(s.W, s.H)
	image.ResampleMode = Enum.ResamplerMode.Pixelated
	image.ScaleType = Enum.ScaleType.Stretch
end

--- Create a new ImageLabel showing a sprite.
function Sprites.New(spriteName: string, parent: Instance?): ImageLabel
	local img = Instance.new("ImageLabel")
	img.BackgroundTransparency = 1
	img.BorderSizePixel = 0
	img.Name = spriteName
	Sprites.Apply(img, spriteName)
	if parent then img.Parent = parent end
	return img
end

function Sprites.Has(spriteName: string): boolean return Sprites.Sprites[spriteName] ~= nil end

--- SERVER ONLY. Open Cloud uploads give a Decal id; ImageLabels need the Image id inside it, and Roblox
--- will not tell outsiders which is which. The server can load its own decal and read the texture off it.
--- Call once at startup, then send Sheets ids to clients (see WorldInit) so everyone uses the resolved ids.
function Sprites.ResolveOnServer(): { [number]: string }
	local InsertService = game:GetService("InsertService")
	local out = {}
	for i, sheet in ipairs(Sprites.Sheets) do
		local id = tonumber(string.match(sheet.Id, "%d+"))
		if id and id > 0 and not sheet.Resolved then
			local ok, model = pcall(function() return InsertService:LoadAsset(id) end)
			if ok and model then
				local decal = model:FindFirstChildWhichIsA("Decal", true)
				local texture = if decal then decal.Texture else ""
				local imageId = string.match(texture, "[?&]id=(%d+)") or string.match(texture, "rbxassetid://(%d+)")
				if imageId then
					sheet.Id = "rbxassetid://" .. imageId
					sheet.Resolved = true
					print(("[Sprites] sheet %d: decal %d -> image %s"):format(i, id, imageId))
				else
					-- No decal inside: the id is already an image id (setid was used). Keep it.
					sheet.Resolved = true
				end
				model:Destroy()
			else
				warn(("[Sprites] could not load asset %d to resolve it (%s); using it as is"):format(id, tostring(model)))
			end
		end
		out[i] = sheet.Id
	end
	return out
end

--- CLIENT: apply the ids the server resolved before building any UI.
function Sprites.ApplySheetIds(ids: { [number]: string }?)
	if not ids then return end
	for i, id in pairs(ids) do
		if Sprites.Sheets[i] and type(id) == "string" then Sprites.Sheets[i].Id = id end
	end
end

return Sprites
