// Sprite sheet packer + Roblox Lua module generator.
// Roblox images are capped at 1024x1024, so we pack into as many 1024 sheets as needed.

/**
 * items: [{ name, canvas }]. Returns [{ canvas, width, height, sprites: { name: {x,y,w,h} } }]
 * Shelf packing, tallest first. Good enough for pixel art; MaxRects is overkill here.
 */
export function packSprites(items, env, { padding = 1, maxSize = 1024, powerOfTwo = true } = {}) {
  const sorted = [...items].sort((a, b) => b.canvas.height - a.canvas.height || b.canvas.width - a.canvas.width);
  const sheets = [];
  let remaining = sorted;
  while (remaining.length) {
    const { placed, leftover, width, height } = packOne(remaining, padding, maxSize);
    if (!placed.length) {
      const big = remaining[0];
      throw new Error(`sprite "${big.name}" (${big.canvas.width}x${big.canvas.height}) exceeds max sheet size ${maxSize}`);
    }
    const W = powerOfTwo ? pot(width) : width, H = powerOfTwo ? pot(height) : height;
    const canvas = env.createCanvas(W, H);
    const ctx = canvas.getContext('2d');
    ctx.imageSmoothingEnabled = false;
    const sprites = {};
    for (const p of placed) {
      ctx.drawImage(p.canvas, p.x, p.y);
      sprites[p.name] = { x: p.x, y: p.y, w: p.canvas.width, h: p.canvas.height };
    }
    sheets.push({ canvas, width: W, height: H, sprites });
    remaining = leftover;
  }
  return sheets;
}

function packOne(items, padding, maxSize) {
  // Try every POT target width; among full fits keep the smallest POT area, then the squarest.
  let best = null;
  for (let target = 64; target <= maxSize; target *= 2) {
    const r = shelf(items, padding, target, maxSize);
    if (r.leftover.length) continue;
    const W = pot(r.width), H = pot(r.height), area = W * H, sq = Math.abs(W - H);
    if (!best || area < best.area || (area === best.area && sq < best.sq)) best = { r, area, sq };
  }
  return best ? best.r : shelf(items, padding, maxSize, maxSize);
}

function shelf(items, padding, width, maxHeight) {
  const placed = [], leftover = [];
  let x = padding, y = padding, rowH = 0, usedW = 0, usedH = 0;
  for (const it of items) {
    const w = it.canvas.width, h = it.canvas.height;
    if (w + padding * 2 > width) { leftover.push(it); continue; }
    if (x + w + padding > width) { x = padding; y += rowH + padding; rowH = 0; }
    if (y + h + padding > maxHeight) { leftover.push(it); continue; }
    placed.push({ ...it, x, y });
    x += w + padding; rowH = Math.max(rowH, h);
    usedW = Math.max(usedW, x); usedH = Math.max(usedH, y + h + padding);
  }
  return { placed, leftover, width: usedW, height: usedH };
}

function pot(n) { let p = 1; while (p < n) p *= 2; return p; }

const ALPHA = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

/**
 * Embedded pixel data for a sheet: palette + run-length encoded indices, so Roblox can rebuild the image at
 * runtime with EditableImage and you can press Play without uploading anything.
 * Runs string: groups of 3 chars [indexHi][indexLo][runLength-1] in the 64-char alphabet (max 4096 colors, runs of 64).
 */
export function encodeSheetPixels(canvas) {
  const { width, height } = canvas;
  const d = canvas.getContext('2d').getImageData(0, 0, width, height).data;
  const palette = [], index = new Map();
  let runs = '', prev = -1, count = 0;
  const flush = () => { while (count > 0) { const n = Math.min(64, count); runs += ALPHA[prev >> 6] + ALPHA[prev & 63] + ALPHA[n - 1]; count -= n; } };
  for (let i = 0; i < d.length; i += 4) {
    const a = d[i + 3];
    const key = a === 0 ? 0 : ((d[i] << 24) | (d[i + 1] << 16) | (d[i + 2] << 8) | a) >>> 0;
    let idx = index.get(key);
    if (idx == null) {
      if (palette.length >= 4096) throw new Error('sheet has more than 4096 colors; embedding is meant for pixel art. Set "embed": false in roblox/sheet.json and upload instead.');
      idx = palette.length; index.set(key, idx); palette.push(a === 0 ? [0, 0, 0, 0] : [d[i], d[i + 1], d[i + 2], a]);
    }
    if (idx === prev) count++; else { flush(); prev = idx; count = 1; }
  }
  flush();
  return { width, height, palette, runs };
}

/** Reference decoder (mirrors the Luau one in Sprites.lua); used by tests. Returns RGBA bytes. */
export function decodeSheetPixels({ width, height, palette, runs }) {
  const out = new Uint8Array(width * height * 4);
  const look = c => ALPHA.indexOf(c);
  let pos = 0;
  for (let i = 0; i < runs.length; i += 3) {
    const color = palette[look(runs[i]) * 64 + look(runs[i + 1])];
    const n = look(runs[i + 2]) + 1;
    for (let k = 0; k < n; k++) { out[pos++] = color[0]; out[pos++] = color[1]; out[pos++] = color[2]; out[pos++] = color[3]; }
  }
  if (pos !== out.length) throw new Error(`decoded ${pos / 4} pixels, expected ${width * height}`);
  return out;
}

export function toSheetDataLua(sheets) {
  const L = ['-- GENERATED by The Warehouse. Embedded sprite sheet pixels (palette + run-length). Do not edit.', '-- Used only while a sheet has no Roblox asset id. See docs/ROBLOX_SETUP.md.', 'return {'];
  sheets.forEach((s, i) => {
    const e = encodeSheetPixels(s.canvas);
    L.push(`\t[${i + 1}] = {`);
    L.push(`\t\tWidth = ${e.width}, Height = ${e.height},`);
    L.push(`\t\tPalette = {${e.palette.map(c => `{${c.join(',')}}`).join(',')}},`);
    // Split long strings so no single source line is enormous.
    L.push(`\t\tRuns = table.concat({`);
    for (let k = 0; k < e.runs.length; k += 120) L.push(`\t\t\t"${e.runs.slice(k, k + 120)}",`);
    L.push(`\t\t}),`);
    L.push(`\t},`);
  });
  L.push('}');
  return L.join('\n') + '\n';
}

/** Lua ModuleScript: sprite rects + helpers. Falls back to the embedded pixels (EditableImage) when a sheet has no asset id. */
export function toLua(sheets, { assetIds = {}, moduleName = 'Sprites' } = {}) {
  const M = moduleName;
  const L = [];
  L.push('-- GENERATED by The Warehouse (warehouse roblox build). Do not edit by hand; edit scenes/ and rebuild.');
  L.push('local AssetService = game:GetService("AssetService")');
  L.push('');
  L.push(`local ${M} = {}`);
  L.push('');
  L.push(`${M}.Sheets = {`);
  sheets.forEach((s, i) => {
    const idv = assetIds[i] || assetIds[String(i)] || 0;
    L.push(`\t[${i + 1}] = { Id = "rbxassetid://${idv}", Width = ${s.width}, Height = ${s.height} },`);
  });
  L.push('}');
  L.push('');
  L.push(`${M}.Sprites = {`);
  sheets.forEach((s, i) => {
    for (const [name, r] of Object.entries(s.sprites).sort()) {
      L.push(`\t[${JSON.stringify(name)}] = { Sheet = ${i + 1}, X = ${r.x}, Y = ${r.y}, W = ${r.w}, H = ${r.h} },`);
    }
  });
  L.push('}');
  L.push('');
  L.push('-- Embedded pixels (SheetData.lua next to this module) let the game run before anything is uploaded.');
  L.push('local sheetDataModule = script.Parent and script.Parent:FindFirstChild("SheetData")');
  L.push('local SheetData = if sheetDataModule then require(sheetDataModule) else nil');
  L.push('local editables = {}');
  L.push('');
  L.push(`local ALPHA = "${ALPHA}"`);
  L.push('local LOOKUP = {}');
  L.push('for i = 1, 64 do LOOKUP[string.byte(ALPHA, i)] = i - 1 end');
  L.push('');
  L.push('--- Decode one embedded sheet into an RGBA8 buffer (pure Luau, no Roblox APIs).');
  L.push(`function ${M}.DecodePixels(data)`);
  L.push('\tlocal w, h = data.Width, data.Height');
  L.push('\tlocal buf = buffer.create(w * h * 4)');
  L.push('\tlocal pal, runs = data.Palette, data.Runs');
  L.push('\tlocal pos = 0');
  L.push('\tfor i = 1, #runs, 3 do');
  L.push('\t\tlocal a, b, c = string.byte(runs, i, i + 2)');
  L.push('\t\tlocal color = pal[LOOKUP[a] * 64 + LOOKUP[b] + 1]');
  L.push('\t\tlocal r, g, bl, al = color[1], color[2], color[3], color[4]');
  L.push('\t\tfor _ = 1, LOOKUP[c] + 1 do');
  L.push('\t\t\tbuffer.writeu8(buf, pos, r)');
  L.push('\t\t\tbuffer.writeu8(buf, pos + 1, g)');
  L.push('\t\t\tbuffer.writeu8(buf, pos + 2, bl)');
  L.push('\t\t\tbuffer.writeu8(buf, pos + 3, al)');
  L.push('\t\t\tpos += 4');
  L.push('\t\tend');
  L.push('\tend');
  L.push('\treturn buf, w, h');
  L.push('end');
  L.push('');
  L.push('local function editableFor(sheetIndex)');
  L.push('\tif editables[sheetIndex] ~= nil then return editables[sheetIndex] or nil end');
  L.push('\tlocal data = SheetData and SheetData[sheetIndex]');
  L.push('\tif not data then editables[sheetIndex] = false return nil end');
  L.push('\tlocal ok, result = pcall(function()');
  L.push(`\t\tlocal buf, w, h = ${M}.DecodePixels(data)`);
  L.push('\t\tlocal img = AssetService:CreateEditableImage({ Size = Vector2.new(w, h) })');
  L.push('\t\timg:WritePixelsBuffer(Vector2.zero, Vector2.new(w, h), buf)');
  L.push('\t\treturn img');
  L.push('\tend)');
  L.push('\tif not ok then warn("[Sprites] could not build embedded sheet " .. sheetIndex .. ": " .. tostring(result)) editables[sheetIndex] = false return nil end');
  L.push('\teditables[sheetIndex] = result');
  L.push('\treturn result');
  L.push('end');
  L.push('');
  L.push(`function ${M}.HasEmbedded(sheetIndex: number?): boolean`);
  L.push('\treturn SheetData ~= nil and SheetData[sheetIndex or 1] ~= nil');
  L.push('end');
  L.push('');
  L.push(`--- Point an ImageLabel/ImageButton at a named sprite. Keeps pixels crisp.`);
  L.push(`function ${M}.Apply(image: ImageLabel | ImageButton, spriteName: string)`);
  L.push(`\tlocal s = ${M}.Sprites[spriteName]`);
  L.push(`\tif not s then warn("[Sprites] unknown sprite " .. tostring(spriteName)) return end`);
  L.push(`\tlocal sheet = ${M}.Sheets[s.Sheet]`);
  L.push(`\tif sheet.Id ~= "rbxassetid://0" then`);
  L.push(`\t\timage.Image = sheet.Id`);
  L.push(`\telse`);
  L.push(`\t\tlocal editable = editableFor(s.Sheet)`);
  L.push(`\t\tif editable then`);
  L.push(`\t\t\timage.ImageContent = Content.fromObject(editable)`);
  L.push(`\t\telse`);
  L.push(`\t\t\twarn("[Sprites] sheet " .. s.Sheet .. " has no asset id and no embedded pixels. Run: warehouse roblox build")`);
  L.push(`\t\tend`);
  L.push(`\tend`);
  L.push(`\timage.ImageRectOffset = Vector2.new(s.X, s.Y)`);
  L.push(`\timage.ImageRectSize = Vector2.new(s.W, s.H)`);
  L.push(`\timage.ResampleMode = Enum.ResamplerMode.Pixelated`);
  L.push(`\timage.ScaleType = Enum.ScaleType.Stretch`);
  L.push(`end`);
  L.push('');
  L.push(`--- Create a new ImageLabel showing a sprite.`);
  L.push(`function ${M}.New(spriteName: string, parent: Instance?): ImageLabel`);
  L.push(`\tlocal img = Instance.new("ImageLabel")`);
  L.push(`\timg.BackgroundTransparency = 1`);
  L.push(`\timg.BorderSizePixel = 0`);
  L.push(`\timg.Name = spriteName`);
  L.push(`\t${M}.Apply(img, spriteName)`);
  L.push(`\tif parent then img.Parent = parent end`);
  L.push(`\treturn img`);
  L.push(`end`);
  L.push('');
  L.push(`function ${M}.Has(spriteName: string): boolean return ${M}.Sprites[spriteName] ~= nil end`);
  L.push('');
  L.push(`return ${M}`);
  return L.join('\n') + '\n';
}

export function toJson(sheets, assetIds = {}) {
  return sheets.map((s, i) => ({ index: i, assetId: assetIds[i] || null, width: s.width, height: s.height, sprites: s.sprites }));
}
