// Sprite sheet packer + Roblox Lua module generator.
// Roblox images are capped at 1024x1024, so we pack into as many 1024 sheets as needed.

/**
 * items: [{ name, canvas }]. Returns [{ canvas, width, height, sprites: { name: {x,y,w,h} } }]
 * Shelf packing, tallest first. Good enough for pixel art; MaxRects is overkill here.
 */
export function packSprites(items, env, { padding = 1, maxSize = 1024, powerOfTwo = true } = {}) {
  const sorted = [...items].sort((a, b) => b.canvas.height - a.canvas.height || b.canvas.width - a.canvas.width);
  const sheets = [];
  let remaining = sorted;
  while (remaining.length) {
    const { placed, leftover, width, height } = packOne(remaining, padding, maxSize);
    if (!placed.length) {
      const big = remaining[0];
      throw new Error(`sprite "${big.name}" (${big.canvas.width}x${big.canvas.height}) exceeds max sheet size ${maxSize}`);
    }
    const W = powerOfTwo ? pot(width) : width, H = powerOfTwo ? pot(height) : height;
    const canvas = env.createCanvas(W, H);
    const ctx = canvas.getContext('2d');
    ctx.imageSmoothingEnabled = false;
    const sprites = {};
    for (const p of placed) {
      ctx.drawImage(p.canvas, p.x, p.y);
      sprites[p.name] = { x: p.x, y: p.y, w: p.canvas.width, h: p.canvas.height };
    }
    sheets.push({ canvas, width: W, height: H, sprites });
    remaining = leftover;
  }
  return sheets;
}

function packOne(items, padding, maxSize) {
  // Try every POT target width; among full fits keep the smallest POT area, then the squarest.
  let best = null;
  for (let target = 64; target <= maxSize; target *= 2) {
    const r = shelf(items, padding, target, maxSize);
    if (r.leftover.length) continue;
    const W = pot(r.width), H = pot(r.height), area = W * H, sq = Math.abs(W - H);
    if (!best || area < best.area || (area === best.area && sq < best.sq)) best = { r, area, sq };
  }
  return best ? best.r : shelf(items, padding, maxSize, maxSize);
}

function shelf(items, padding, width, maxHeight) {
  const placed = [], leftover = [];
  let x = padding, y = padding, rowH = 0, usedW = 0, usedH = 0;
  for (const it of items) {
    const w = it.canvas.width, h = it.canvas.height;
    if (w + padding * 2 > width) { leftover.push(it); continue; }
    if (x + w + padding > width) { x = padding; y += rowH + padding; rowH = 0; }
    if (y + h + padding > maxHeight) { leftover.push(it); continue; }
    placed.push({ ...it, x, y });
    x += w + padding; rowH = Math.max(rowH, h);
    usedW = Math.max(usedW, x); usedH = Math.max(usedH, y + h + padding);
  }
  return { placed, leftover, width: usedW, height: usedH };
}

function pot(n) { let p = 1; while (p < n) p *= 2; return p; }

/** Lua ModuleScript: sprite rects + helper that applies a sprite to an ImageLabel/ImageButton. */
export function toLua(sheets, { assetIds = {}, moduleName = 'Sprites' } = {}) {
  const L = [];
  L.push('-- GENERATED by The Warehouse (warehouse roblox build). Do not edit by hand; edit scenes/ and rebuild.');
  L.push(`local ${moduleName} = {}`);
  L.push('');
  L.push(`${moduleName}.Sheets = {`);
  sheets.forEach((s, i) => {
    const idv = assetIds[i] || assetIds[String(i)] || 0;
    L.push(`\t[${i + 1}] = { Id = "rbxassetid://${idv}", Width = ${s.width}, Height = ${s.height} },`);
  });
  L.push('}');
  L.push('');
  L.push(`${moduleName}.Sprites = {`);
  sheets.forEach((s, i) => {
    for (const [name, r] of Object.entries(s.sprites).sort()) {
      L.push(`\t[${JSON.stringify(name)}] = { Sheet = ${i + 1}, X = ${r.x}, Y = ${r.y}, W = ${r.w}, H = ${r.h} },`);
    }
  });
  L.push('}');
  L.push('');
  L.push(`--- Point an ImageLabel/ImageButton at a named sprite. Keeps pixels crisp.`);
  L.push(`function ${moduleName}.Apply(image: ImageLabel | ImageButton, spriteName: string)`);
  L.push(`\tlocal s = ${moduleName}.Sprites[spriteName]`);
  L.push(`\tif not s then warn("[Sprites] unknown sprite " .. tostring(spriteName)) return end`);
  L.push(`\tlocal sheet = ${moduleName}.Sheets[s.Sheet]`);
  L.push(`\timage.Image = sheet.Id`);
  L.push(`\timage.ImageRectOffset = Vector2.new(s.X, s.Y)`);
  L.push(`\timage.ImageRectSize = Vector2.new(s.W, s.H)`);
  L.push(`\timage.ResampleMode = Enum.ResamplerMode.Pixelated`);
  L.push(`\timage.ScaleType = Enum.ScaleType.Stretch`);
  L.push(`end`);
  L.push('');
  L.push(`--- Create a new ImageLabel showing a sprite.`);
  L.push(`function ${moduleName}.New(spriteName: string, parent: Instance?): ImageLabel`);
  L.push(`\tlocal img = Instance.new("ImageLabel")`);
  L.push(`\timg.BackgroundTransparency = 1`);
  L.push(`\timg.BorderSizePixel = 0`);
  L.push(`\timg.Name = spriteName`);
  L.push(`\t${moduleName}.Apply(img, spriteName)`);
  L.push(`\tif parent then img.Parent = parent end`);
  L.push(`\treturn img`);
  L.push(`end`);
  L.push('');
  L.push(`function ${moduleName}.Has(spriteName: string): boolean return ${moduleName}.Sprites[spriteName] ~= nil end`);
  L.push('');
  L.push('--- SERVER ONLY. Open Cloud uploads give a Decal id; ImageLabels need the Image id inside it, and Roblox');
  L.push('--- will not tell outsiders which is which. The server can load its own decal and read the texture off it.');
  L.push('--- Call once at startup, then send Sheets ids to clients (see WorldInit) so everyone uses the resolved ids.');
  L.push(`function ${moduleName}.ResolveOnServer(): { [number]: string }`);
  L.push('\tlocal InsertService = game:GetService("InsertService")');
  L.push('\tlocal out = {}');
  L.push(`\tfor i, sheet in ipairs(${moduleName}.Sheets) do`);
  L.push('\t\tlocal id = tonumber(string.match(sheet.Id, "%d+"))');
  L.push('\t\tif id and id > 0 and not sheet.Resolved then');
  L.push('\t\t\tlocal ok, model = pcall(function() return InsertService:LoadAsset(id) end)');
  L.push('\t\t\tif ok and model then');
  L.push('\t\t\t\tlocal decal = model:FindFirstChildWhichIsA("Decal", true)');
  L.push('\t\t\t\tlocal texture = if decal then decal.Texture else ""');
  L.push('\t\t\t\tlocal imageId = string.match(texture, "[?&]id=(%d+)") or string.match(texture, "rbxassetid://(%d+)")');
  L.push('\t\t\t\tif imageId then');
  L.push('\t\t\t\t\tsheet.Id = "rbxassetid://" .. imageId');
  L.push('\t\t\t\t\tsheet.Resolved = true');
  L.push('\t\t\t\t\tprint(("[Sprites] sheet %d: decal %d -> image %s"):format(i, id, imageId))');
  L.push('\t\t\t\telse');
  L.push('\t\t\t\t\t-- No decal inside: the id is already an image id (setid was used). Keep it.');
  L.push('\t\t\t\t\tsheet.Resolved = true');
  L.push('\t\t\t\tend');
  L.push('\t\t\t\tmodel:Destroy()');
  L.push('\t\t\telse');
  L.push('\t\t\t\twarn(("[Sprites] could not load asset %d to resolve it (%s); using it as is"):format(id, tostring(model)))');
  L.push('\t\t\tend');
  L.push('\t\tend');
  L.push('\t\tout[i] = sheet.Id');
  L.push('\tend');
  L.push('\treturn out');
  L.push('end');
  L.push('');
  L.push('--- CLIENT: apply the ids the server resolved before building any UI.');
  L.push(`function ${moduleName}.ApplySheetIds(ids: { [number]: string }?)`);
  L.push('\tif not ids then return end');
  L.push('\tfor i, id in pairs(ids) do');
  L.push(`\t\tif ${moduleName}.Sheets[i] and type(id) == "string" then ${moduleName}.Sheets[i].Id = id end`);
  L.push('\tend');
  L.push('end');
  L.push('');
  L.push(`return ${moduleName}`);
  return L.join('\n') + '\n';
}

export function toJson(sheets, assetIds = {}) {
  return sheets.map((s, i) => ({ index: i, assetId: assetIds[i] || null, width: s.width, height: s.height, sprites: s.sprites }));
}
